<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Photo Booth</title>
<style>
    body {
        background-color: #d78a76; /* Light red background */
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100vh;
        margin: 0;
    }
    #video {
        border: 5px solid white; /* White border for video element */
        box-shadow: 0 4px 8px rgba(0,0,0,0.5); /* Shadow for depth */
    }
    #gallery {
        margin-top: 20px;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
    }
    #gallery img {
        width: 100px;
        height: auto;
        margin: 5px;
        border: 3px solid white; /* White border for images */
        box-shadow: 0 2px 4px rgba(0,0,0,0.5); /* Consistent styling with video */
    }
    button {
        padding: 10px 20px;
        font-size: 16px;
        margin-top: 10px;
        cursor: pointer;
        background-color: white;
        border: none;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.25);
        transition: background-color 0.3s, transform 0.3s;
    }
    button:hover {
        background-color: #f0e2de; /* Lighter tone for interactive element */
        transform: translateY(-2px);
    }
    button:active {
        transform: translateY(1px);
    }
</style>
</head>
<body>
<video id="video" width="640" height="480" autoplay></video>
<button id="snap">Snap Photo</button>
<div id="gallery"></div>

<script>
    const video = document.getElementById('video');
    const canvas = document.createElement('canvas');
    const gallery = document.getElementById('gallery');

    // Get access to the camera
    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
        navigator.mediaDevices.getUserMedia({ video: true })
            .then(function(stream) {
                video.srcObject = stream;
                video.play();
            })
            .catch(function(error) {
                console.error("Error accessing the camera: ", error);
            });
    } else {
        alert('getUserMedia not supported on
